[CmdletBinding()]
param(
    [string]$Target = "win-amd64-msvc2022-py310-release",
    [string]$PythonExe = "python",
    [string]$ConstraintsFile = "",
    [switch]$NoIndex
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = Resolve-Path (Join-Path $ScriptDir "..\..")

if (-not $ConstraintsFile) {
    $ConstraintsFile = Join-Path $RepoRoot "constraints\py310.txt"
}

$VenvDir = Join-Path $RepoRoot ".venvs\$Target"
$VenvPython = Join-Path $VenvDir "Scripts\python.exe"
$WheelhouseDir = Join-Path $RepoRoot "external\wheelhouse\vtk-9.3.1\$Target"
$SdkRoot = Join-Path $RepoRoot "external\install\vtk-9.3.1\$Target\sdk"
$AuditScript = Join-Path $RepoRoot "scripts\validate\audit-environment.py"
$TempDir = Join-Path $RepoRoot ".tmp"

function Invoke-External {
    param(
        [Parameter(Mandatory = $true)]
        [string]$FilePath,
        [string[]]$Arguments = @()
    )

    & $FilePath @Arguments
    if ($LASTEXITCODE -ne 0) {
        $renderedArgs = $Arguments -join " "
        throw "Command failed with exit code ${LASTEXITCODE}: $FilePath $renderedArgs"
    }
}

function Get-VtkWheel {
    param(
        [Parameter(Mandatory = $true)]
        [string]$WheelhousePath
    )

    if (-not (Test-Path $WheelhousePath)) {
        throw "Wheelhouse does not exist: $WheelhousePath"
    }

    $wheels = Get-ChildItem -Path $WheelhousePath -Filter "vtk-*.whl" | Sort-Object LastWriteTimeUtc -Descending
    if (-not $wheels) {
        throw "No vtk wheel was found in $WheelhousePath. Build VTK and generate the wheel first."
    }

    return $wheels[0].FullName
}

function Get-InstalledVtkVersion {
    param(
        [Parameter(Mandatory = $true)]
        [string]$PythonPath
    )

    $version = & $PythonPath -c "import importlib.metadata; print(importlib.metadata.version('vtk'))"
    if ($LASTEXITCODE -ne 0 -or -not $version) {
        throw "Unable to determine installed vtk version in the target venv."
    }

    return $version.Trim()
}

function Get-VtkModulesDir {
    param(
        [Parameter(Mandatory = $true)]
        [string]$PythonPath
    )

    $vtkModulesDir = & $PythonPath -c "import importlib.util; spec = importlib.util.find_spec('vtkmodules'); print(next(iter(spec.submodule_search_locations)) if spec and spec.submodule_search_locations else '')"
    if ($LASTEXITCODE -ne 0 -or -not $vtkModulesDir) {
        throw "Unable to determine the vtkmodules package location in the target venv."
    }

    $vtkModulesDir = $vtkModulesDir.Trim()
    if (-not (Test-Path $vtkModulesDir)) {
        throw "The vtk wheel does not appear to be installed correctly: missing $vtkModulesDir"
    }

    return $vtkModulesDir
}

function Find-QtBinDir {
    $candidates = New-Object System.Collections.Generic.List[string]

    foreach ($envVar in @("QTDIR", "QT_DIR", "Qt5_DIR", "Qt6_DIR")) {
        $value = [Environment]::GetEnvironmentVariable($envVar, "Process")
        if ($value) {
            $candidates.Add((Join-Path $value "bin"))
            $candidates.Add($value)
        }
    }

    $qmake = Get-Command qmake -ErrorAction SilentlyContinue
    if ($qmake) {
        $qmakeDir = Split-Path -Parent $qmake.Source
        $candidates.Add($qmakeDir)
    }

    $candidates.Add("C:\local\qt\bin")

    foreach ($candidate in $candidates) {
        if (-not $candidate) {
            continue
        }
        if ((Test-Path $candidate) -and (Get-ChildItem -Path $candidate -Filter "Qt*Core*.dll" -ErrorAction SilentlyContinue | Select-Object -First 1)) {
            return (Resolve-Path $candidate).Path
        }
    }

    return $null
}

function Write-VtkBuildPaths {
    param(
        [Parameter(Mandatory = $true)]
        [string]$VtkModulesDir,
        [string[]]$AdditionalPaths = @()
    )

    $buildPathsFile = Join-Path $VtkModulesDir "_build_paths.py"
    $existing = @()
    foreach ($path in $AdditionalPaths) {
        if (-not $path) {
            continue
        }
        $resolved = Resolve-Path $path -ErrorAction SilentlyContinue
        if ($resolved) {
            $existing += $resolved.Path
        }
    }

    $uniquePaths = $existing | Select-Object -Unique
    $quoted = $uniquePaths | ForEach-Object { "r'$($_ -replace '\\', '\\')'" }
    $content = @(
        "# Auto-generated by scripts/windows/sync-venv.ps1",
        "paths=["
    )
    $content += $quoted | ForEach-Object { "    $_," }
    $content += "]"

    Set-Content -Path $buildPathsFile -Value $content -Encoding UTF8
    Write-Host "Wrote VTK build-path hints to $buildPathsFile"
}

function Stage-VtkRuntimeWindows {
    param(
        [Parameter(Mandatory = $true)]
        [string]$PythonPath,
        [Parameter(Mandatory = $true)]
        [string]$SdkRootPath
    )

    if ($env:OS -ne "Windows_NT") {
        return
    }

    $sdkBinDir = Join-Path $SdkRootPath "bin"
    if (-not (Test-Path $sdkBinDir)) {
        throw "Expected VTK SDK runtime directory was not found: $sdkBinDir"
    }

    $vtkModulesDir = Get-VtkModulesDir -PythonPath $PythonPath
    $sitePackagesDir = Split-Path -Parent $vtkModulesDir
    $runtimeBinDir = Join-Path $sitePackagesDir "bin"
    New-Item -ItemType Directory -Force -Path $runtimeBinDir | Out-Null

    $dlls = Get-ChildItem -Path $sdkBinDir -Filter "*.dll"
    if (-not $dlls) {
        throw "No VTK DLLs were found in $sdkBinDir"
    }

    foreach ($dll in $dlls) {
        Copy-Item -Path $dll.FullName -Destination (Join-Path $runtimeBinDir $dll.Name) -Force
    }

    $qtBinDir = Find-QtBinDir
    Write-VtkBuildPaths -VtkModulesDir $vtkModulesDir -AdditionalPaths @($qtBinDir)

    Write-Host "Staged $($dlls.Count) VTK runtime DLLs into $runtimeBinDir"
    if ($qtBinDir) {
        Write-Host "Detected Qt runtime at $qtBinDir"
    }
    else {
        Write-Warning "No Qt runtime directory was detected. Importing vtkRenderingQt may still fail."
    }
}

if (-not (Test-Path $VenvPython)) {
    Invoke-External -FilePath $PythonExe -Arguments @("-m", "venv", $VenvDir)
}

Invoke-External -FilePath $VenvPython -Arguments @($AuditScript, "--mode", "strict", "--target-venv", $VenvDir)
$vtkWheel = Get-VtkWheel -WheelhousePath $WheelhouseDir
Invoke-External -FilePath $VenvPython -Arguments @("-m", "pip", "install", "--no-deps", "--force-reinstall", $vtkWheel)
Stage-VtkRuntimeWindows -PythonPath $VenvPython -SdkRootPath $SdkRoot

$installedVtkVersion = Get-InstalledVtkVersion -PythonPath $VenvPython
New-Item -ItemType Directory -Force -Path $TempDir | Out-Null
$VtkConstraintFile = Join-Path $TempDir "vtk-constraint-$Target.txt"
Set-Content -Path $VtkConstraintFile -Value "vtk===$installedVtkVersion" -Encoding UTF8

$pyvistaArgs = @(
    "-m", "pip", "install",
    "--constraint", $ConstraintsFile,
    "--constraint", $VtkConstraintFile,
    "pyvista"
)

if ($NoIndex) {
    $pyvistaArgs = @(
        "-m", "pip", "install",
        "--no-index",
        "--find-links", $WheelhouseDir,
        "--constraint", $ConstraintsFile,
        "--constraint", $VtkConstraintFile,
        "pyvista"
    )
}

Invoke-External -FilePath $VenvPython -Arguments $pyvistaArgs
Invoke-External -FilePath $VenvPython -Arguments @("-m", "pip", "install", (Join-Path $RepoRoot "packages\codecpp"))
Invoke-External -FilePath $VenvPython -Arguments @("-m", "pip", "install", "-e", (Join-Path $RepoRoot "packages\codepy"))
Invoke-External -FilePath $VenvPython -Arguments @("-m", "pip", "install", "-e", (Join-Path $RepoRoot "packages\pmanager"))
